### ISSUE TITLE
你好， 请问这个可以结合 WRNavigationBar 一起使用吗？

### ISSUE THREAD

**Issue by aidevjoe** [wangrui460/BackBtnEventIntercept_swift#1]
我尝试将 **BackBtnEventIntercept_swift** 的代码加入到 **WRNavigationBar** 中， 但是右滑时会导致闪屏，请问有解决方法吗

**Comment by wangrui460** [comment]
哈，我就在刚刚更新了WRNavigationBar的代码，因为之前文件夹WRNavigationBar没有更新，所以你说的问题可能确实存在，现在更新一下应该就ok了，如果有问题可以加我qq1204607318。另外给你推荐swift版本的WRNavigationBar：https://github.com/wangrui460/WRNavigationBar_swift
也非常👍

**Comment by aidevjoe** [comment]
可能我的表达有问题，我详细描述下
我目前使用你的 **WRNavigationBar_swift** 库来修改导航栏外观，非常好用🙏
现在我想使用 **BackBtnEventIntercept_swift** 这个库拦截系统返回手势处理一些操作
但是这两个库一起使用的话会导致冲突，所以我尝试把 **BackBtnEventIntercept_swift** 的代码加入到 **WRNavigationBar_swift**，  但是右滑时会导致闪屏

**Comment by aidevjoe** [comment]
把 BackBtnEventIntercept_swift 的代码加入到 WRNavigationBar_swift中之后，可以正常拦截系统返回时间， 但是右滑时会导致闪屏， 不知道是不是结合之后代码问题，请问可以帮助解决吗

**Comment by wangrui460** [comment]
`
public func navigationBar(_ navigationBar: UINavigationBar, shouldPop item: UINavigationItem) -> Bool
{
    var shouldPop = true
    let currentVC = self.topViewController
    shouldPop = (currentVC?.currentViewControllerShouldPop())!
    
    if (shouldPop == true)
    {
        if let topVC = topViewController,
            let coor = topVC.transitionCoordinator, coor.initiallyInteractive {
            if #available(iOS 10.0, *) {
                coor.notifyWhenInteractionChanges({ (context) in
                    self.dealInteractionChanges(context)
                })
            } else {
                coor.notifyWhenInteractionEnds({ (context) in
                    self.dealInteractionChanges(context)
                })
            }
            return true
        }
        
        let itemCount = navigationBar.items?.count ?? 0
        let n = viewControllers.count >= itemCount ? 2 : 1
        let popToVC = viewControllers[viewControllers.count - n]
        
        popToViewController(popToVC, animated: true)
        return true
        
        
    }
    else
    {
        // 让系统backIndicator 按钮透明度恢复为1
        for subview in navigationBar.subviews
        {
            if (0.0 < subview.alpha && subview.alpha < 1.0) {
                UIView.animate(withDuration: 0.25, animations: {
                    subview.alpha = 1.0
                })
            }
        }
        return false
    }
}
`

简单的写了一下

**Comment by aidevjoe** [comment]
非常感谢， 它工作了。
